[package]
name = "servemg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
base64ct = "1.6.0"
sha2 = "0.10.8"
tokio = { version = "1.36.0", features = ["full"] }
tower = "0.4.13"
