services:
  servemg:
    image: ghcr.io/broot5/servemg:latest
    container_name: servemg
    restart: unless-stopped
    environment:
      - DB_URL=postgresql://postgres:db_password@postgres:5432
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY_ID=s3_user
      - S3_SECRET_ACCESS_KEY=s3_password
      - S3_REGION=us-east-1
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: db_password

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=s3_user
      - MINIO_ROOT_PASSWORD=s3_password
      - MINIO_REGION=us-east-1
    command: server /data --console-address ":9001"
